Several minor changes and updates.
golemfactory/golem-docs pull request #239
Opened 2024-02-26 11:05 UTC by FOMFNY

2024-02-26 13:47 UTC, stan7123 commented on src/pages/docs/providers/gpu/gpu-golem-live.md
> +
...even when recording golem image again

2024-02-26 13:49 UTC, stan7123 requested changes
There is no information about what GLM/h price. Should this be in docs or only info for beta testers?

2024-02-26 13:50 UTC, stan7123 reviewed
I added one more point about changing USB port: https://discord.com/channels/1159813841316745261/1196782569954496592/1210159703716266025

2024-02-29 09:02 UTC, jalas167 approved these changes

2024-02-29 09:02 UTC, merged