requestor-provider-interaction
golemfactory/golem-docs pull request #262
Opened 2024-04-11 14:10 UTC by jalas167

2024-04-12 11:03 UTC, cryptobench requested changes

2024-04-12 11:03 UTC, cryptobench commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +The provider sends the invoice when the agreement is terminated. The agreement may be terminated by the requestor (when he has no more tasks to execute for this provider), or by the provider (i.e. ag
```suggestion
The agreement can be terminated either by the requestor, if there are no more tasks to be executed with the provider, or by the provider due to expiration of the agreed duration or the requestor's failure to timely accept a debit note. Upon termination of the agreement, the provider will send an invoice.
```

2024-04-12 11:03 UTC, cryptobench commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +The requestor accepts the payment and the payment driver used by Yagna will handle the payment process.
```suggestion
The requestor accepts the payment and the payment driver used by Yagna will handle the processing of the payment.
```

2024-04-15 14:49 UTC, jalas167 commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +description: A description of a typical interaction between a requestor and provider, illustrated with JS SDK events.
ok, some of the events are generated in task-executor, however finally the article is based on the one from golem-js to make it more universal.

2024-04-15 15:01 UTC, jalas167 commented on src/navigation/docs.js
> +        title: 'Golem concepts for developers',
let's discuss it, from these 2 I would prefer Golem System Mechanics, but that sounds for me like sth very complicated while concepts for me sound like sth basic and essential to know.

2024-04-15 15:03 UTC, jalas167 commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +We have run a simple requestor script employing the Task Model and logged emitted events to show you how internally Golem Network works. The events in the list below are filtered (similar events are
```suggestion
We have run a simple requestor script employing the Task Model and logged emitted events to show you how internally Golem Network works. The events in the list below are filtered (similar events are removed to make the story more readable) and sometimes reordered to keep related topics in the same section.
```

2024-04-15 15:05 UTC, jalas167 commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +Then the Requestor is presented with proposals. In the example below, you can see some detailed information from the offer: the provider's details, its resources, and capabilities.
I will handle this another way, the true is that while we say a proposal is a pair (demand and offer), in fact providers proposal is an offer and reference to demand/proposal and requestor proposal is a updated demand and reference to providers's offer.

2024-04-15 15:27 UTC, jalas167 commented on src/pages/docs/creators/javascript/examples/accessing-internet.md
> +Note: This example shows how to use the outbound whitelist to install a npm package on a provider. It is recommended to install additional packages in a directory that is defined as `VOLUME` in the i
that will come with int he other pr

2024-04-18 13:40 UTC, cryptobench requested changes

2024-04-18 13:40 UTC, cryptobench commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +Internally all the commands are organized as `scripts`, that are sent and executed on a provider. There are several commands (depending on the time of type of the runtime utilized) available for the
"depending on the time of type of the runtime utilized"

I think something is wrong here

2024-04-18 13:40 UTC, cryptobench commented on src/pages/docs/creators/javascript/examples/composing-tasks.md
> +In this example, we show how to use `remoteProcess.waitForExit()` to terminate the process. Note that in the current implementation, the exit caused by timeout will terminate the activity on a provid
```suggestion
In this example, we show how to use `remoteProcess.waitForExit()` to terminate the process. Note that in the current implementation, the exit caused by timeout will terminate the activity on a provider, therefore the user cannot run another command on that specific provider. The task executor will instead run the task on another provider.
```

2024-04-18 13:57 UTC, jalas167 commented on src/pages/docs/creators/common/requestor-provider-interaction.md
> +Internally all the commands are organized as `scripts`, that are sent and executed on a provider. There are several commands (depending on the time of type of the runtime utilized) available for the
```suggestion
Internally all the commands are organized as `scripts`, that are sent and executed on a provider. There are several commands (depending on the type of the runtime utilized) available for the requestor. For a VM, you can `start`, `deploy`, `run`, `transfer`, and `terminate`. So, as you see, even the initial image deployment is sent and executed as a `script`, but the user does not need to bother about it, as it is all handled by the Golem SDKs.
```

2024-04-18 14:01 UTC, cryptobench approved these changes

2024-04-18 14:01 UTC, merged